### ISSUE TITLE
Recording response when run start record is showing ios version ?

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [inanevin/hh_screen_recorder#1]
<img width="946" alt="Screen Shot 2022-12-10 at 19 04 36" src="https://user-images.githubusercontent.com/13627112/206854293-49ec798a-fe93-4414-8ce7-7827c28926de.png">

**Comment by inanevin** [comment]
iOS implementation is still in the works, this repo is highly experimental atm :)

**Comment by nguyenleanhkhoa** [comment]
Can you finish this part soon for ios. , I really need this function for ios T_T
